INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project One', 'Tech', 40000, 'May fifteenth', 'August twentieth');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Two', 'Art', 5000, 'June first', 'September eleventh');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Three', 'Tech', 42000, 'March fourth', 'August first');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Four', 'Art', 1500, 'May fifteenth', 'August twentieth');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Five', 'Education', 6000, 'June fifteenth', 'September twentieth');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Six', 'Education', 60000, 'January second', 'June first');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Seven', 'Art', 40000, 'February tenth', 'August twentieth');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Eight', 'Tech', 500, 'March first', 'December first');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Nine', 'Fashion', 1400, 'July first', 'November tenth');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project Ten', 'Tech', 65000, 'August first', 'October twentieth');

INSERT INTO users (name, age) VALUES ('Fred', 25);
INSERT INTO users (name, age) VALUES ('Albert', 50);
INSERT INTO users (name, age) VALUES ('Andrew', 27);
INSERT INTO users (name, age) VALUES ('Monica', 33);
INSERT INTO users (name, age) VALUES ('Hermione', 45);
INSERT INTO users (name, age) VALUES ('Luna', 24);
INSERT INTO users (name, age) VALUES ('Jessica', 30);
INSERT INTO users (name, age) VALUES ('Harry', 47);
INSERT INTO users (name, age) VALUES ('George', 60);
INSERT INTO users (name, age) VALUES ('Bran', 38);
INSERT INTO users (name, age) VALUES ('Arya', 25);
INSERT INTO users (name, age) VALUES ('Sansa', 32);
INSERT INTO users (name, age) VALUES ('Eleanor', 34);
INSERT INTO users (name, age) VALUES ('Chidi', 35);
INSERT INTO users (name, age) VALUES ('Jameela', 38);
INSERT INTO users (name, age) VALUES ('Indya', 28);
INSERT INTO users (name, age) VALUES ('Beanie', 44);
INSERT INTO users (name, age) VALUES ('Trace', 39);
INSERT INTO users (name, age) VALUES ('MJ', 33);
INSERT INTO users (name, age) VALUES ('Sophia', 38);

INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 20, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 11, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750, 15, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (860, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (780, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 29, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (730, 30, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 21, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 22, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (240, 23, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (560, 24, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 25, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 26, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (780, 27, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 28, 5);
